project:
  type: website

website:
  title: "Amy Heather"
  navbar:
    left:
      - projects/index.qmd
      - training/index.qmd
      - contributions/index.qmd
      - publications/index.qmd
      - packages/index.qmd
      - community/index.qmd
    right:
      - icon: github
        text: GitHub
        href: https://github.com/amyheather/amyheather.github.io/

format:
  html:
    theme:
      - darkly
      - styles/theme.scss
    css:
      - styles/styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">