---
title: Community
---

## Clubs

* NHS model reuse club
* University of Exeter St Lukes coding club

## Conferences

**RPySoc 2025:** November 2025

**Simulation Workshop 2025 (SW25):** 31st March - 2nd April 2025

**European Health Economics Association (EuHEA)**: July 2022

I shared two presentations at this [conference](https://euhea.eu/abstracts_conference_2022.html):

::: {.callout-note title="Exploring the responsiveness of preference-based wellbeing, condition-specific and generic measures in the context of multiple sclerosis" collapse="true"}

**Objectives** The National Institute of Health and Care Excellence, which gives guidance on health/social care interventions to be provided by the UK National Health Service, has recently stated that preference-based-measures (PBMs) of wellbeing may be used in cost-effectiveness analyses, in addition to generic and condition-specific (CS) PBMs of health-related quality of life. We aimed to assess the comparative responsiveness of wellbeing, generic and CS PBMs in the context of multiple sclerosis (MS).

**Methods** The MS Register (MSR) is a cohort, representative of the UK population of people with MS. In September 2019, March 2020 and September 2020, MSR respondents completed wellbeing PBMs– the ICEpop CAPability measure for Adults (ICECAP-A) and Adult Social Care Outcomes Toolkit (ASCOT); CS PBMs– the MS Impact Scale Eight Dimensions (MSIS-8D) and MSIS-8D-Patient (MSIS-8D-P); and a generic PBM- the EQ-5D-3L. They also completed the Fatigue Severity Scale, MS Walking Scale-12, Hospital Anxiety and Depression Scale, and a bespoke measure of ‘illness events’ that may have occurred between time-points e.g. a relapse, a new symptom, leaving employment due to MS. Responsiveness of the PBMs was compared in relation to changes in fatigue, mobility, anxiety and depression between time-points, and by the occurrence of illness events. Standardised response means and Cohen’s D were calculated, and t-tests used to assess change. Multivariable pooled OLS regression analyses were undertaken for each PBM with standard errors clustered by respondent. Variables were standardised to enable comparison.

**Results** 1,742 individuals gave responses for at least two consecutive time-points. Overall, CS PBMs were the most responsive, followed by ICECAP-A, ASCOT and lastly the EQ-5D. For example, coefficients (95% CIs) in relation to changes in anxiety were: MSIS-8D -0.253 (-0.304,-0.202); MSIS-8D-P -0.248 (-0.300,-0.197); ICECAP-A -0.195 (-0.243,-0.147); ASCOT -0.170 (-0.217,-0.122); EQ-5D -0.162 (-0.219,-0.105). The PBMs were more responsive to changes in anxiety and depression than to changes in mobility or fatigue. They showed little responsiveness, and no consistent pattern, in relation to illness events.

**Discussion** Our results support the use of CS and wellbeing PBMs alongside the EQ-5D, to maximise the potential of detecting treatment benefits in cost-effectiveness analyses of treatments for MS. The lack of responsiveness to illness events may reflect limitations in the content or design of the illness events measure, however this was informed by a systematic search of qualitative literature and devised with a MS patient involvement group. Alternatively, the finding may be indicative of limited responsiveness of the PBMs to key illness events in the lives of people with MS.

:::

::: {.callout-note title="Health state values from a representative UK sample of people with Multiple Sclerosis (MS): A comparison of the generic, condition-specific, and condition-specific patient-weighted values" collapse="true"}

**Objectives** The EQ-5D is a generic, preference-based-measure (PBM) of health-related quality of life, recommended by the National Institute of Health and Care Excellence in the UK as a source of health state values (HSVs) for the calculation of quality-adjusted life-years (QALYs). Concerns have been raised, however, about the sensitivity of the EQ-5D to differences and changes in the health-related quality of life of people with multiple sclerosis (MS). This has led to the development of MS-specific PBMs, such as the MS Impact Scale Eight Dimensions (MSIS-8D) and the MSIS-8D-Patient (MSIS-8D-P), which are based on public and patient preferences respectively. We aimed to compare the discriminative validity of the EQ-5D, MSIS-8D and MSIS-8D-P across a range of demographic and clinical characteristics, using data from a large UK cohort of people with MS.

**Methods** UK MS Register responses from 2011 to 2019 were analysed descriptively
and using multivariable linear regression to investigate the strength of independent relationships between demographic/clinical characteristics and HSVs on each of the PBMs. Robust regression was used as residuals did not meet assumptions of normality/homoscedasticity. Continuous variables were centred.

**Results** There were 14,385 respondents. Mean age was 55.3 (11.4) years and 72.8% were female. Mean disease severity score on the Expanded Disability Status Scale (EDSS) was 5.1 (2.0). Mean EQ-5D, MSIS-8D and MSIS-8D-P values were 0.562 (0.308), 0.603 (0.18) and 0.643 (0.173) respectively. Compared to EQ-5D values, mean MSIS-8D and MSIS-8D-P values were generally higher and their absolute differences between groups by demographic/clinical characteristics were smaller. Regression analysis indicated that HSVs were significantly negatively associated with disease severity (EDSS) (p<0.001) and significantly positively associated with age (p<0.001) on all three measures.

**Discussion** This study provides a new source of generic and MS-specific HSVs, based on a recent, representative sample of people with MS in the UK, which can be used in economic evaluations. Many cost effectiveness analyses of treatments for MS still rely on a source of EQ-5D values collected in 2005. The HSVs reported here will better reflect current treatment practices, which have altered the profile of the UK MS population. The smaller differences between subgroups of people with MS that were identified by the MS-specific PBMs are likely due to the narrower range of HSVs for the MSIS-8D (0.079 to 0.882) and MSIS-8D-P (0.138 to 0.893), compared to the EQ-5D (-0.594 to 1). This is a common characteristic of PBMs other than the EQ-5D, and is an important factor to consider when comparing cost-effectiveness results based on different sources of HSVs.

:::
